version: 2
jobs:
  build:
    docker:
      - image: circleci/java:8
    steps:
      - checkout
      - run: <command>
  test:
    docker:
        - image: circleci/java:8
    steps:
      - checkout
      - run: echo "success"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
